emails:
  events:
    "Jump5_Vol_1":
        subject: "Jump5 Vol.1 Confirmation" 
        body: |
          Hello {name},

          Thanks for registering for Jump5 Vol.1.
          Please show this QR code during registration to get audition number.
    "Funk_Battle":
      subject: "Funk Battle Confirmation"
      body: |
        Hello {name},

        Thanks for registering for Funk Battle.
        Please show this QR code during registration to get audition number.

    "Mock_Street_Element":
      subject: "Confirmation email for Mock Street Element"
      body: |
        Hello {name},

        Thanks for registering for Mock Street Element.
        Please show this QR code during registration to get audition number.
    
    "PopEvent":
      subject: "Confirmation email for Pop Event"
      body: |
        Hello {name},

        Thanks for registering for Pop Event.
        Please show this QR code during registration to get audition number.
    
    "Street_Elements_Vol__5":
      subject: "Confirmation email for Street Element Vol.5"
      body: |
        Hello {name},

        Thanks for registering for Street Element Vol.5.
        Please show the QR code during registration to get your audition number.

        Thank you.

        Regards,
        Soul Extreme
        
    